services:
  web:
    image: frontend:dev-build
    ports:
      - 3000:3000
    environment:
      CONTAINER: "true"
      FORCE_COLOR: "true"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
  api:
    image: backend:dev-build
    ports:
      - 8000:8000
    depends_on:
      - minio
    environment:
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: bucket
    volumes:
      - ./backend:/home/python/
  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-05T09-16-26Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data
  createDevBucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/bucket;
      /usr/bin/mc policy set public myminio/bucket;
      "

volumes:
  data: